### ISSUE TITLE
When no inverters, it doesn't fail gracefully

### ISSUE THREAD

**Issue by yaleman** [yaleman/pygoodwe#1]
It should probably just raise a simpler error than "ugh, die".
```
2019-10-10 07:17:42,774 Failed to call GoodWe API
Traceback (most recent call last):
  File "/usr/local/bin/goodwe2pvoutput", line 69, in <module>
    do_the_thing()
  File "/usr/local/bin/goodwe2pvoutput", line 55, in do_the_thing
    password=CONFIG.get('goodwe', 'password')
  File "/usr/local/lib/python3.7/dist-packages/pygoodwe/__init__.py", line 338, in __init__
    super().__init__(system_id, account, password, skipload)
  File "/usr/local/lib/python3.7/dist-packages/pygoodwe/__init__.py", line 105, in __init__
    self.getCurrentReadings(raw=True)
  File "/usr/local/lib/python3.7/dist-packages/pygoodwe/__init__.py", line 351, in getCurrentReadin
    if len(self.data['inverter']):
KeyError: 'inverter'
```

**Comment by yaleman** [comment]
Fixed in 9e32d37c
